[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Falcon Documentation"
authors = [{name = "FRC 5190", email = "programming@frc5190.org"}]
dynamic = ["version", "description"]
